# Outgoing email settings

production:
  delivery_method: :smtp
  smtp_settings:
    tls: true
    enable_starttls_auto: true
    address: "smtp.gmail.com"
    port: '587'
    domain: "smtp.gmail.com"
    authentication: :plain
    user_name: "heroku.redmine.mail@gmail.com"
    password: "r3dm1n3h3r0ku"