# Outgoing email settings

production:
  delivery_method: :smtp
  smtp_settings:
    address: smptp.gmail.com
    port: 587
    domain: gmail.com
    authentication: :login
    user_name: "heroku.redmine.mail@gmail.com"
    password: "r3dm1n3h3r0ku"
    tls: true
